# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/debian-9.4"
  config.vm.box_version = "201803.24.0"

  config.vm.network "private_network", type: "dhcp"
  #config.vm.synced_folder "../targets", "/targets"

  config.vm.provider "virtualbox" do |vb|
     vb.name = "Client_Attack_Lab"
     vb.memory = "1024"
  end

  config.vm.provision "file", source: "../targets", destination: "~/targets"
  config.vm.provision "shell", path: "provision.sh"
  config.vm.provision "shell", path: "finalize.sh", privileged: false
end
